//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KimialPG
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateToken", Namespace="https://rt.sizpay.com/")]
    public partial class GenerateToken : object
    {
        
        private string ReturnURLField;
        
        private string OrderIDField;
        
        private string DocDateField;
        
        private long AmountField;
        
        private string ExtraInfField;
        
        private string InvoiceNoField;
        
        private KimialPG.AppExtraInf AppExtraInfField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        private string MerchantIDField;
        
        private string TerminalIDField;
        
        private string SignDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReturnURL
        {
            get
            {
                return this.ReturnURLField;
            }
            set
            {
                this.ReturnURLField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DocDate
        {
            get
            {
                return this.DocDateField;
            }
            set
            {
                this.DocDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ExtraInf
        {
            get
            {
                return this.ExtraInfField;
            }
            set
            {
                this.ExtraInfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string InvoiceNo
        {
            get
            {
                return this.InvoiceNoField;
            }
            set
            {
                this.InvoiceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public KimialPG.AppExtraInf AppExtraInf
        {
            get
            {
                return this.AppExtraInfField;
            }
            set
            {
                this.AppExtraInfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string MerchantID
        {
            get
            {
                return this.MerchantIDField;
            }
            set
            {
                this.MerchantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string TerminalID
        {
            get
            {
                return this.TerminalIDField;
            }
            set
            {
                this.TerminalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string SignData
        {
            get
            {
                return this.SignDataField;
            }
            set
            {
                this.SignDataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppExtraInf", Namespace="https://rt.sizpay.com/")]
    public partial class AppExtraInf : object
    {
        
        private string PayerNmField;
        
        private string PayerMobileField;
        
        private string PayerEmailField;
        
        private string PayerIPField;
        
        private string DescrField;
        
        private long PayTitleIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PayerNm
        {
            get
            {
                return this.PayerNmField;
            }
            set
            {
                this.PayerNmField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PayerMobile
        {
            get
            {
                return this.PayerMobileField;
            }
            set
            {
                this.PayerMobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PayerEmail
        {
            get
            {
                return this.PayerEmailField;
            }
            set
            {
                this.PayerEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PayerIP
        {
            get
            {
                return this.PayerIPField;
            }
            set
            {
                this.PayerIPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Descr
        {
            get
            {
                return this.DescrField;
            }
            set
            {
                this.DescrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long PayTitleID
        {
            get
            {
                return this.PayTitleIDField;
            }
            set
            {
                this.PayTitleIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="https://rt.sizpay.com/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.Peyment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.ConfReverse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.ReportResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.TokenResponse))]
    public partial class Response : object
    {
        
        private int ResCodField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ResCod
        {
            get
            {
                return this.ResCodField;
            }
            set
            {
                this.ResCodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Peyment", Namespace="https://rt.sizpay.com/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.ConfReverse))]
    public partial class Peyment : KimialPG.Response
    {
        
        private string MerchantIDField;
        
        private string TerminalIDField;
        
        private string OrderIDField;
        
        private long RefNoField;
        
        private long AmountField;
        
        private string InvoiceNoField;
        
        private string ExtraInfField;
        
        private KimialPG.AppExtraInf AppExtraInfField;
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MerchantID
        {
            get
            {
                return this.MerchantIDField;
            }
            set
            {
                this.MerchantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TerminalID
        {
            get
            {
                return this.TerminalIDField;
            }
            set
            {
                this.TerminalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long RefNo
        {
            get
            {
                return this.RefNoField;
            }
            set
            {
                this.RefNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string InvoiceNo
        {
            get
            {
                return this.InvoiceNoField;
            }
            set
            {
                this.InvoiceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ExtraInf
        {
            get
            {
                return this.ExtraInfField;
            }
            set
            {
                this.ExtraInfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public KimialPG.AppExtraInf AppExtraInf
        {
            get
            {
                return this.AppExtraInfField;
            }
            set
            {
                this.AppExtraInfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfReverse", Namespace="https://rt.sizpay.com/")]
    public partial class ConfReverse : KimialPG.Peyment
    {
        
        private string CardNoField;
        
        private string TransDateField;
        
        private string TransNoField;
        
        private string TraceNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CardNo
        {
            get
            {
                return this.CardNoField;
            }
            set
            {
                this.CardNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransDate
        {
            get
            {
                return this.TransDateField;
            }
            set
            {
                this.TransDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransNo
        {
            get
            {
                return this.TransNoField;
            }
            set
            {
                this.TransNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TraceNo
        {
            get
            {
                return this.TraceNoField;
            }
            set
            {
                this.TraceNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportResponse", Namespace="https://rt.sizpay.com/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.GenerateToken))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.AppExtraInf))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.TokenResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.Response))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.PaymentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.ConfReverse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.Peyment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(KimialPG.RepTrnsInfByInvoiceRequest))]
    public partial class ReportResponse : KimialPG.Response
    {
        
        private object DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenResponse", Namespace="https://rt.sizpay.com/")]
    public partial class TokenResponse : KimialPG.Response
    {
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentRequest", Namespace="https://rt.sizpay.com/")]
    public partial class PaymentRequest : object
    {
        
        private string MerchantIDField;
        
        private string TerminalIDField;
        
        private string TokenField;
        
        private string SignDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MerchantID
        {
            get
            {
                return this.MerchantIDField;
            }
            set
            {
                this.MerchantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TerminalID
        {
            get
            {
                return this.TerminalIDField;
            }
            set
            {
                this.TerminalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token
        {
            get
            {
                return this.TokenField;
            }
            set
            {
                this.TokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SignData
        {
            get
            {
                return this.SignDataField;
            }
            set
            {
                this.SignDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RepTrnsInfByInvoiceRequest", Namespace="https://rt.sizpay.com/")]
    public partial class RepTrnsInfByInvoiceRequest : object
    {
        
        private string MerchantIDField;
        
        private string TerminalIDField;
        
        private string InvoiceNoField;
        
        private string InvoiceDateField;
        
        private string SignDataField;
        
        private string UserNameField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MerchantID
        {
            get
            {
                return this.MerchantIDField;
            }
            set
            {
                this.MerchantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TerminalID
        {
            get
            {
                return this.TerminalIDField;
            }
            set
            {
                this.TerminalIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string InvoiceNo
        {
            get
            {
                return this.InvoiceNoField;
            }
            set
            {
                this.InvoiceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string InvoiceDate
        {
            get
            {
                return this.InvoiceDateField;
            }
            set
            {
                this.InvoiceDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SignData
        {
            get
            {
                return this.SignDataField;
            }
            set
            {
                this.SignDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://rt.sizpay.com/", ConfigurationName="KimialPG.KimiaIPGRouteServiceSoap")]
    public interface KimiaIPGRouteServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rt.sizpay.com/WebServiceTest", ReplyAction="*")]
        System.Threading.Tasks.Task<KimialPG.WebServiceTestResponse> WebServiceTestAsync(KimialPG.WebServiceTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rt.sizpay.com/GetToken2", ReplyAction="*")]
        System.Threading.Tasks.Task<KimialPG.GetToken2Response> GetToken2Async(KimialPG.GetToken2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rt.sizpay.com/GetToken", ReplyAction="*")]
        System.Threading.Tasks.Task<KimialPG.GetTokenResponse> GetTokenAsync(KimialPG.GetTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rt.sizpay.com/Confirm", ReplyAction="*")]
        System.Threading.Tasks.Task<KimialPG.ConfirmResponse> ConfirmAsync(KimialPG.ConfirmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rt.sizpay.com/Confirm2", ReplyAction="*")]
        System.Threading.Tasks.Task<KimialPG.Confirm2Response> Confirm2Async(KimialPG.Confirm2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rt.sizpay.com/Reverse", ReplyAction="*")]
        System.Threading.Tasks.Task<KimialPG.ReverseResponse> ReverseAsync(KimialPG.ReverseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rt.sizpay.com/Reverse2", ReplyAction="*")]
        System.Threading.Tasks.Task<KimialPG.Reverse2Response> Reverse2Async(KimialPG.Reverse2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://rt.sizpay.com/TransactionListByInvoiceNo", ReplyAction="*")]
        System.Threading.Tasks.Task<KimialPG.TransactionListByInvoiceNoResponse> TransactionListByInvoiceNoAsync(KimialPG.TransactionListByInvoiceNoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebServiceTestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebServiceTest", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.WebServiceTestRequestBody Body;
        
        public WebServiceTestRequest()
        {
        }
        
        public WebServiceTestRequest(KimialPG.WebServiceTestRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class WebServiceTestRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string prmName;
        
        public WebServiceTestRequestBody()
        {
        }
        
        public WebServiceTestRequestBody(string prmName)
        {
            this.prmName = prmName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WebServiceTestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WebServiceTestResponse", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.WebServiceTestResponseBody Body;
        
        public WebServiceTestResponse()
        {
        }
        
        public WebServiceTestResponse(KimialPG.WebServiceTestResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class WebServiceTestResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string WebServiceTestResult;
        
        public WebServiceTestResponseBody()
        {
        }
        
        public WebServiceTestResponseBody(string WebServiceTestResult)
        {
            this.WebServiceTestResult = WebServiceTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToken2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToken2", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.GetToken2RequestBody Body;
        
        public GetToken2Request()
        {
        }
        
        public GetToken2Request(KimialPG.GetToken2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class GetToken2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TerminalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DocDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OrderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ReturnURL;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ExtraInf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string InvoiceNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AppExtraInf;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SignData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Password;
        
        public GetToken2RequestBody()
        {
        }
        
        public GetToken2RequestBody(string MerchantID, string TerminalID, string Amount, string DocDate, string OrderID, string ReturnURL, string ExtraInf, string InvoiceNo, string AppExtraInf, string SignData, string UserName, string Password)
        {
            this.MerchantID = MerchantID;
            this.TerminalID = TerminalID;
            this.Amount = Amount;
            this.DocDate = DocDate;
            this.OrderID = OrderID;
            this.ReturnURL = ReturnURL;
            this.ExtraInf = ExtraInf;
            this.InvoiceNo = InvoiceNo;
            this.AppExtraInf = AppExtraInf;
            this.SignData = SignData;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetToken2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToken2Response", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.GetToken2ResponseBody Body;
        
        public GetToken2Response()
        {
        }
        
        public GetToken2Response(KimialPG.GetToken2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class GetToken2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetToken2Result;
        
        public GetToken2ResponseBody()
        {
        }
        
        public GetToken2ResponseBody(string GetToken2Result)
        {
            this.GetToken2Result = GetToken2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetToken", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.GetTokenRequestBody Body;
        
        public GetTokenRequest()
        {
        }
        
        public GetTokenRequest(KimialPG.GetTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class GetTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KimialPG.GenerateToken GenerateTokenData;
        
        public GetTokenRequestBody()
        {
        }
        
        public GetTokenRequestBody(KimialPG.GenerateToken GenerateTokenData)
        {
            this.GenerateTokenData = GenerateTokenData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokenResponse", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.GetTokenResponseBody Body;
        
        public GetTokenResponse()
        {
        }
        
        public GetTokenResponse(KimialPG.GetTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class GetTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KimialPG.TokenResponse GetTokenResult;
        
        public GetTokenResponseBody()
        {
        }
        
        public GetTokenResponseBody(KimialPG.TokenResponse GetTokenResult)
        {
            this.GetTokenResult = GetTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Confirm", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.ConfirmRequestBody Body;
        
        public ConfirmRequest()
        {
        }
        
        public ConfirmRequest(KimialPG.ConfirmRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class ConfirmRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KimialPG.PaymentRequest prmData;
        
        public ConfirmRequestBody()
        {
        }
        
        public ConfirmRequestBody(KimialPG.PaymentRequest prmData)
        {
            this.prmData = prmData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConfirmResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConfirmResponse", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.ConfirmResponseBody Body;
        
        public ConfirmResponse()
        {
        }
        
        public ConfirmResponse(KimialPG.ConfirmResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class ConfirmResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KimialPG.ConfReverse ConfirmResult;
        
        public ConfirmResponseBody()
        {
        }
        
        public ConfirmResponseBody(KimialPG.ConfReverse ConfirmResult)
        {
            this.ConfirmResult = ConfirmResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Confirm2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Confirm2", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.Confirm2RequestBody Body;
        
        public Confirm2Request()
        {
        }
        
        public Confirm2Request(KimialPG.Confirm2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class Confirm2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TerminalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SignData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password;
        
        public Confirm2RequestBody()
        {
        }
        
        public Confirm2RequestBody(string MerchantID, string TerminalID, string Token, string SignData, string UserName, string Password)
        {
            this.MerchantID = MerchantID;
            this.TerminalID = TerminalID;
            this.Token = Token;
            this.SignData = SignData;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Confirm2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Confirm2Response", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.Confirm2ResponseBody Body;
        
        public Confirm2Response()
        {
        }
        
        public Confirm2Response(KimialPG.Confirm2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class Confirm2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Confirm2Result;
        
        public Confirm2ResponseBody()
        {
        }
        
        public Confirm2ResponseBody(string Confirm2Result)
        {
            this.Confirm2Result = Confirm2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reverse", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.ReverseRequestBody Body;
        
        public ReverseRequest()
        {
        }
        
        public ReverseRequest(KimialPG.ReverseRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class ReverseRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KimialPG.PaymentRequest prmData;
        
        public ReverseRequestBody()
        {
        }
        
        public ReverseRequestBody(KimialPG.PaymentRequest prmData)
        {
            this.prmData = prmData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseResponse", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.ReverseResponseBody Body;
        
        public ReverseResponse()
        {
        }
        
        public ReverseResponse(KimialPG.ReverseResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class ReverseResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KimialPG.ConfReverse ReverseResult;
        
        public ReverseResponseBody()
        {
        }
        
        public ReverseResponseBody(KimialPG.ConfReverse ReverseResult)
        {
            this.ReverseResult = ReverseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Reverse2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reverse2", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.Reverse2RequestBody Body;
        
        public Reverse2Request()
        {
        }
        
        public Reverse2Request(KimialPG.Reverse2RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class Reverse2RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MerchantID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TerminalID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SignData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password;
        
        public Reverse2RequestBody()
        {
        }
        
        public Reverse2RequestBody(string MerchantID, string TerminalID, string Token, string SignData, string UserName, string Password)
        {
            this.MerchantID = MerchantID;
            this.TerminalID = TerminalID;
            this.Token = Token;
            this.SignData = SignData;
            this.UserName = UserName;
            this.Password = Password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Reverse2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Reverse2Response", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.Reverse2ResponseBody Body;
        
        public Reverse2Response()
        {
        }
        
        public Reverse2Response(KimialPG.Reverse2ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class Reverse2ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Reverse2Result;
        
        public Reverse2ResponseBody()
        {
        }
        
        public Reverse2ResponseBody(string Reverse2Result)
        {
            this.Reverse2Result = Reverse2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionListByInvoiceNoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransactionListByInvoiceNo", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.TransactionListByInvoiceNoRequestBody Body;
        
        public TransactionListByInvoiceNoRequest()
        {
        }
        
        public TransactionListByInvoiceNoRequest(KimialPG.TransactionListByInvoiceNoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class TransactionListByInvoiceNoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KimialPG.RepTrnsInfByInvoiceRequest prmData;
        
        public TransactionListByInvoiceNoRequestBody()
        {
        }
        
        public TransactionListByInvoiceNoRequestBody(KimialPG.RepTrnsInfByInvoiceRequest prmData)
        {
            this.prmData = prmData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionListByInvoiceNoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransactionListByInvoiceNoResponse", Namespace="https://rt.sizpay.com/", Order=0)]
        public KimialPG.TransactionListByInvoiceNoResponseBody Body;
        
        public TransactionListByInvoiceNoResponse()
        {
        }
        
        public TransactionListByInvoiceNoResponse(KimialPG.TransactionListByInvoiceNoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://rt.sizpay.com/")]
    public partial class TransactionListByInvoiceNoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public KimialPG.ReportResponse TransactionListByInvoiceNoResult;
        
        public TransactionListByInvoiceNoResponseBody()
        {
        }
        
        public TransactionListByInvoiceNoResponseBody(KimialPG.ReportResponse TransactionListByInvoiceNoResult)
        {
            this.TransactionListByInvoiceNoResult = TransactionListByInvoiceNoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface KimiaIPGRouteServiceSoapChannel : KimialPG.KimiaIPGRouteServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class KimiaIPGRouteServiceSoapClient : System.ServiceModel.ClientBase<KimialPG.KimiaIPGRouteServiceSoap>, KimialPG.KimiaIPGRouteServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public KimiaIPGRouteServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(KimiaIPGRouteServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), KimiaIPGRouteServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KimiaIPGRouteServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(KimiaIPGRouteServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KimiaIPGRouteServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(KimiaIPGRouteServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public KimiaIPGRouteServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KimialPG.WebServiceTestResponse> KimialPG.KimiaIPGRouteServiceSoap.WebServiceTestAsync(KimialPG.WebServiceTestRequest request)
        {
            return base.Channel.WebServiceTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<KimialPG.WebServiceTestResponse> WebServiceTestAsync(string prmName)
        {
            KimialPG.WebServiceTestRequest inValue = new KimialPG.WebServiceTestRequest();
            inValue.Body = new KimialPG.WebServiceTestRequestBody();
            inValue.Body.prmName = prmName;
            return ((KimialPG.KimiaIPGRouteServiceSoap)(this)).WebServiceTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KimialPG.GetToken2Response> KimialPG.KimiaIPGRouteServiceSoap.GetToken2Async(KimialPG.GetToken2Request request)
        {
            return base.Channel.GetToken2Async(request);
        }
        
        public System.Threading.Tasks.Task<KimialPG.GetToken2Response> GetToken2Async(string MerchantID, string TerminalID, string Amount, string DocDate, string OrderID, string ReturnURL, string ExtraInf, string InvoiceNo, string AppExtraInf, string SignData, string UserName, string Password)
        {
            KimialPG.GetToken2Request inValue = new KimialPG.GetToken2Request();
            inValue.Body = new KimialPG.GetToken2RequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.TerminalID = TerminalID;
            inValue.Body.Amount = Amount;
            inValue.Body.DocDate = DocDate;
            inValue.Body.OrderID = OrderID;
            inValue.Body.ReturnURL = ReturnURL;
            inValue.Body.ExtraInf = ExtraInf;
            inValue.Body.InvoiceNo = InvoiceNo;
            inValue.Body.AppExtraInf = AppExtraInf;
            inValue.Body.SignData = SignData;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((KimialPG.KimiaIPGRouteServiceSoap)(this)).GetToken2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KimialPG.GetTokenResponse> KimialPG.KimiaIPGRouteServiceSoap.GetTokenAsync(KimialPG.GetTokenRequest request)
        {
            return base.Channel.GetTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<KimialPG.GetTokenResponse> GetTokenAsync(KimialPG.GenerateToken GenerateTokenData)
        {
            KimialPG.GetTokenRequest inValue = new KimialPG.GetTokenRequest();
            inValue.Body = new KimialPG.GetTokenRequestBody();
            inValue.Body.GenerateTokenData = GenerateTokenData;
            return ((KimialPG.KimiaIPGRouteServiceSoap)(this)).GetTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KimialPG.ConfirmResponse> KimialPG.KimiaIPGRouteServiceSoap.ConfirmAsync(KimialPG.ConfirmRequest request)
        {
            return base.Channel.ConfirmAsync(request);
        }
        
        public System.Threading.Tasks.Task<KimialPG.ConfirmResponse> ConfirmAsync(KimialPG.PaymentRequest prmData)
        {
            KimialPG.ConfirmRequest inValue = new KimialPG.ConfirmRequest();
            inValue.Body = new KimialPG.ConfirmRequestBody();
            inValue.Body.prmData = prmData;
            return ((KimialPG.KimiaIPGRouteServiceSoap)(this)).ConfirmAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KimialPG.Confirm2Response> KimialPG.KimiaIPGRouteServiceSoap.Confirm2Async(KimialPG.Confirm2Request request)
        {
            return base.Channel.Confirm2Async(request);
        }
        
        public System.Threading.Tasks.Task<KimialPG.Confirm2Response> Confirm2Async(string MerchantID, string TerminalID, string Token, string SignData, string UserName, string Password)
        {
            KimialPG.Confirm2Request inValue = new KimialPG.Confirm2Request();
            inValue.Body = new KimialPG.Confirm2RequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.TerminalID = TerminalID;
            inValue.Body.Token = Token;
            inValue.Body.SignData = SignData;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((KimialPG.KimiaIPGRouteServiceSoap)(this)).Confirm2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KimialPG.ReverseResponse> KimialPG.KimiaIPGRouteServiceSoap.ReverseAsync(KimialPG.ReverseRequest request)
        {
            return base.Channel.ReverseAsync(request);
        }
        
        public System.Threading.Tasks.Task<KimialPG.ReverseResponse> ReverseAsync(KimialPG.PaymentRequest prmData)
        {
            KimialPG.ReverseRequest inValue = new KimialPG.ReverseRequest();
            inValue.Body = new KimialPG.ReverseRequestBody();
            inValue.Body.prmData = prmData;
            return ((KimialPG.KimiaIPGRouteServiceSoap)(this)).ReverseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KimialPG.Reverse2Response> KimialPG.KimiaIPGRouteServiceSoap.Reverse2Async(KimialPG.Reverse2Request request)
        {
            return base.Channel.Reverse2Async(request);
        }
        
        public System.Threading.Tasks.Task<KimialPG.Reverse2Response> Reverse2Async(string MerchantID, string TerminalID, string Token, string SignData, string UserName, string Password)
        {
            KimialPG.Reverse2Request inValue = new KimialPG.Reverse2Request();
            inValue.Body = new KimialPG.Reverse2RequestBody();
            inValue.Body.MerchantID = MerchantID;
            inValue.Body.TerminalID = TerminalID;
            inValue.Body.Token = Token;
            inValue.Body.SignData = SignData;
            inValue.Body.UserName = UserName;
            inValue.Body.Password = Password;
            return ((KimialPG.KimiaIPGRouteServiceSoap)(this)).Reverse2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KimialPG.TransactionListByInvoiceNoResponse> KimialPG.KimiaIPGRouteServiceSoap.TransactionListByInvoiceNoAsync(KimialPG.TransactionListByInvoiceNoRequest request)
        {
            return base.Channel.TransactionListByInvoiceNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<KimialPG.TransactionListByInvoiceNoResponse> TransactionListByInvoiceNoAsync(KimialPG.RepTrnsInfByInvoiceRequest prmData)
        {
            KimialPG.TransactionListByInvoiceNoRequest inValue = new KimialPG.TransactionListByInvoiceNoRequest();
            inValue.Body = new KimialPG.TransactionListByInvoiceNoRequestBody();
            inValue.Body.prmData = prmData;
            return ((KimialPG.KimiaIPGRouteServiceSoap)(this)).TransactionListByInvoiceNoAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KimiaIPGRouteServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.KimiaIPGRouteServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.KimiaIPGRouteServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://rt.sizpay.ir/KimiaIPGRouteService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.KimiaIPGRouteServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://rt.sizpay.ir/KimiaIPGRouteService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            KimiaIPGRouteServiceSoap,
            
            KimiaIPGRouteServiceSoap12,
        }
    }
}
